### ISSUE TITLE
License

### ISSUE THREAD

**Issue by gnunicode** [strophe/strophejs-plugin-vcard#2]
There isn't a license file for this - I'm guessing the license is the same as for strophe? @jcbrand this is for the LibreJS support - I'm getting there eventually though I have exams coming up at the moment so it might take a while

**Comment by sualko** [comment]
https://github.com/strophe/strophejs-plugin-vcard/blob/c69ae358265b5095e8efe6939f07b767d34ebb9b/package.json#L23

cheers
